# Default values for app-chart.
frontend:
  replicaCount: 1
  image:
    repository: lorenzogaetani/lab3-cpo-frontend
    tag: 0.0.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

backend:
  replicaCount: 1
  image:
    repository: lorenzogaetani/lab3-cpo-backend
    tag: 0.0.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080